syntax = "proto3";
package proto.packets;

option csharp_namespace = "TournamentAssistantShared.Models.Packets";

import "models.proto";

// ---- Commands (DO something!) ---- //
message Command {
  message PlaySong {
    models.GameplayParameters gameplay_parameters = 1;
  }

  message ModifyGameplay {
    enum Modifier {
      InvertColors = 0;
      InvertHandedness = 1;
      DisableBlueNotes = 2;
      DisableRedNotes = 3;
    }

    Modifier modifier = 1;
  }

  message ShowColorForStreamSync {
    string color = 1;
  }

  string tournament_id = 11;
  repeated string forward_to = 12;

  oneof type {
    bool return_to_menu = 2;
    bool delay_test_finish = 3;
    bool stream_sync_show_image = 4;
    PlaySong play_song = 6;
    string discord_authorize = 9;
    ModifyGameplay modify_gameplay = 10;
    ShowColorForStreamSync show_color_for_stream_sync = 13;
  }
}